// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: protoc/shortner.proto

package shortener

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LinkShortener_CreateShortLink_FullMethodName = "/shortener_proto.LinkShortener/CreateShortLink"
	LinkShortener_GetOriginalLink_FullMethodName = "/shortener_proto.LinkShortener/GetOriginalLink"
)

// LinkShortenerClient is the client API for LinkShortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkShortenerClient interface {
	CreateShortLink(ctx context.Context, in *CreateShortLinkRequest, opts ...grpc.CallOption) (*CreateShortLinkResponse, error)
	GetOriginalLink(ctx context.Context, in *GetOriginalLinkRequest, opts ...grpc.CallOption) (*GetOriginalLinkResponse, error)
}

type linkShortenerClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkShortenerClient(cc grpc.ClientConnInterface) LinkShortenerClient {
	return &linkShortenerClient{cc}
}

func (c *linkShortenerClient) CreateShortLink(ctx context.Context, in *CreateShortLinkRequest, opts ...grpc.CallOption) (*CreateShortLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShortLinkResponse)
	err := c.cc.Invoke(ctx, LinkShortener_CreateShortLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkShortenerClient) GetOriginalLink(ctx context.Context, in *GetOriginalLinkRequest, opts ...grpc.CallOption) (*GetOriginalLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOriginalLinkResponse)
	err := c.cc.Invoke(ctx, LinkShortener_GetOriginalLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkShortenerServer is the server API for LinkShortener service.
// All implementations must embed UnimplementedLinkShortenerServer
// for forward compatibility.
type LinkShortenerServer interface {
	CreateShortLink(context.Context, *CreateShortLinkRequest) (*CreateShortLinkResponse, error)
	GetOriginalLink(context.Context, *GetOriginalLinkRequest) (*GetOriginalLinkResponse, error)
	mustEmbedUnimplementedLinkShortenerServer()
}

// UnimplementedLinkShortenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLinkShortenerServer struct{}

func (UnimplementedLinkShortenerServer) CreateShortLink(context.Context, *CreateShortLinkRequest) (*CreateShortLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShortLink not implemented")
}
func (UnimplementedLinkShortenerServer) GetOriginalLink(context.Context, *GetOriginalLinkRequest) (*GetOriginalLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOriginalLink not implemented")
}
func (UnimplementedLinkShortenerServer) mustEmbedUnimplementedLinkShortenerServer() {}
func (UnimplementedLinkShortenerServer) testEmbeddedByValue()                       {}

// UnsafeLinkShortenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkShortenerServer will
// result in compilation errors.
type UnsafeLinkShortenerServer interface {
	mustEmbedUnimplementedLinkShortenerServer()
}

func RegisterLinkShortenerServer(s grpc.ServiceRegistrar, srv LinkShortenerServer) {
	// If the following call pancis, it indicates UnimplementedLinkShortenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LinkShortener_ServiceDesc, srv)
}

func _LinkShortener_CreateShortLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShortLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServer).CreateShortLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkShortener_CreateShortLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServer).CreateShortLink(ctx, req.(*CreateShortLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkShortener_GetOriginalLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOriginalLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServer).GetOriginalLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinkShortener_GetOriginalLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServer).GetOriginalLink(ctx, req.(*GetOriginalLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkShortener_ServiceDesc is the grpc.ServiceDesc for LinkShortener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkShortener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shortener_proto.LinkShortener",
	HandlerType: (*LinkShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShortLink",
			Handler:    _LinkShortener_CreateShortLink_Handler,
		},
		{
			MethodName: "GetOriginalLink",
			Handler:    _LinkShortener_GetOriginalLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/shortner.proto",
}
