// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protoc/shortner.proto

package shortener

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Original      string                 `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkRequest) Reset() {
	*x = CreateShortLinkRequest{}
	mi := &file_protoc_shortner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkRequest) ProtoMessage() {}

func (x *CreateShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_shortner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_protoc_shortner_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortLinkRequest) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

type CreateShortLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Short         string                 `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkResponse) Reset() {
	*x = CreateShortLinkResponse{}
	mi := &file_protoc_shortner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkResponse) ProtoMessage() {}

func (x *CreateShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_shortner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_protoc_shortner_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortLinkResponse) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

type GetOriginalLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Short         string                 `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalLinkRequest) Reset() {
	*x = GetOriginalLinkRequest{}
	mi := &file_protoc_shortner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalLinkRequest) ProtoMessage() {}

func (x *GetOriginalLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_shortner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalLinkRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalLinkRequest) Descriptor() ([]byte, []int) {
	return file_protoc_shortner_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalLinkRequest) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

type GetOriginalLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Original      string                 `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalLinkResponse) Reset() {
	*x = GetOriginalLinkResponse{}
	mi := &file_protoc_shortner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalLinkResponse) ProtoMessage() {}

func (x *GetOriginalLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_shortner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalLinkResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalLinkResponse) Descriptor() ([]byte, []int) {
	return file_protoc_shortner_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalLinkResponse) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

var File_protoc_shortner_proto protoreflect.FileDescriptor

const file_protoc_shortner_proto_rawDesc = "" +
	"\n" +
	"\x15protoc/shortner.proto\x12\x0fshortener_proto\x1a\x1cgoogle/api/annotations.proto\"4\n" +
	"\x16CreateShortLinkRequest\x12\x1a\n" +
	"\boriginal\x18\x01 \x01(\tR\boriginal\"/\n" +
	"\x17CreateShortLinkResponse\x12\x14\n" +
	"\x05short\x18\x01 \x01(\tR\x05short\".\n" +
	"\x16GetOriginalLinkRequest\x12\x14\n" +
	"\x05short\x18\x01 \x01(\tR\x05short\"5\n" +
	"\x17GetOriginalLinkResponse\x12\x1a\n" +
	"\boriginal\x18\x01 \x01(\tR\boriginal2\x8c\x02\n" +
	"\rLinkShortener\x12z\n" +
	"\x0fCreateShortLink\x12'.shortener_proto.CreateShortLinkRequest\x1a(.shortener_proto.CreateShortLinkResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/links\x12\x7f\n" +
	"\x0fGetOriginalLink\x12'.shortener_proto.GetOriginalLinkRequest\x1a(.shortener_proto.GetOriginalLinkResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/links/{short}B\"Z grpc-url-shortener/pkg;shortenerb\x06proto3"

var (
	file_protoc_shortner_proto_rawDescOnce sync.Once
	file_protoc_shortner_proto_rawDescData []byte
)

func file_protoc_shortner_proto_rawDescGZIP() []byte {
	file_protoc_shortner_proto_rawDescOnce.Do(func() {
		file_protoc_shortner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_shortner_proto_rawDesc), len(file_protoc_shortner_proto_rawDesc)))
	})
	return file_protoc_shortner_proto_rawDescData
}

var file_protoc_shortner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protoc_shortner_proto_goTypes = []any{
	(*CreateShortLinkRequest)(nil),  // 0: shortener_proto.CreateShortLinkRequest
	(*CreateShortLinkResponse)(nil), // 1: shortener_proto.CreateShortLinkResponse
	(*GetOriginalLinkRequest)(nil),  // 2: shortener_proto.GetOriginalLinkRequest
	(*GetOriginalLinkResponse)(nil), // 3: shortener_proto.GetOriginalLinkResponse
}
var file_protoc_shortner_proto_depIdxs = []int32{
	0, // 0: shortener_proto.LinkShortener.CreateShortLink:input_type -> shortener_proto.CreateShortLinkRequest
	2, // 1: shortener_proto.LinkShortener.GetOriginalLink:input_type -> shortener_proto.GetOriginalLinkRequest
	1, // 2: shortener_proto.LinkShortener.CreateShortLink:output_type -> shortener_proto.CreateShortLinkResponse
	3, // 3: shortener_proto.LinkShortener.GetOriginalLink:output_type -> shortener_proto.GetOriginalLinkResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_shortner_proto_init() }
func file_protoc_shortner_proto_init() {
	if File_protoc_shortner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_shortner_proto_rawDesc), len(file_protoc_shortner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_shortner_proto_goTypes,
		DependencyIndexes: file_protoc_shortner_proto_depIdxs,
		MessageInfos:      file_protoc_shortner_proto_msgTypes,
	}.Build()
	File_protoc_shortner_proto = out.File
	file_protoc_shortner_proto_goTypes = nil
	file_protoc_shortner_proto_depIdxs = nil
}
