version: "3"

tasks: 
  generate: 
    aliases: 
      - gen
    cmds: 
      # для grpc-gateway
      - protoc -I. -Igoogle/api --go_out=./pkg --go_opt=paths=source_relative --go-grpc_out=./pkg --go-grpc_opt=paths=source_relative --grpc-gateway_out=./pkg --grpc-gateway_opt=paths=source_relative ./protoc/shortner.proto
      # - protoc -I protoc protoc/shortner.proto --go_out=./pkg/protoc --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative
      # - protoc -I protoc protoc/shortner.proto --go_out=./pkg/protoc --go_opt=paths=source_relative --go-grpc_out=./pkg/protoc --go-grpc_opt=paths=source_relative